[package]
name = "node_sequential_2_dense_22_matmul_readvariableop_0"
version = "0.1.0"
edition = "2023_10"

[dependencies]
orion = { git = "https://github.com/gizatechxyz/orion.git", rev = "7d84a42" } 
[lib]
sierra-text = true